site_name: Our Notes
site_url: https://github.com/muhammadfarras/kertas-pena
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.footer
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Gelapin
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Terangin
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  generator: false
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/muhammadfarras
    name: Muhammad Farras Ma'ruf's GitHub
copyright: Catatan untuk, Muhammad Faris Ma'ruf & Nu'man Noah Ma'ruf 2023










nav:
  - index.md
  - Information Technology:
    - Learn Linux:
      - Pertama: Technology/Catatan Linux Bible/index.md
      - Using The Shell: Technology/Catatan Linux Bible/01. Using the shell.md
    - Learn MySql:
      - Pertama: Bla bla
      - Kedua: Bla Bla





