site_name: Our Notes
site_url: https://github.com/muhammadfarras/kertas-pena
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.top
    - toc.follow
    - toc.integrate
    - header.autohide
    - navigation.footers
  palette: 
    
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7 
        name: Gelapin
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Terangin
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true 
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  generator: true
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/muhammadfarras
    name: Muhammad Farras Ma'ruf's GitHub
copyright: Catatan untuk, Muhammad Faris Ma'ruf & Nu'man Noah Ma'ruf 2023
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'








nav:
  - index.md
  - Programming Language: 
    - Learn Python:
      - Preface Python: Programming Language/Python/index.md
      - Data Types: Programming Language/Python/01. Data Types.md
      - Conditional and Iteration: Programming Language/Python/02. Conditional and Iteration.md
      - Function Building and Block of Code : Programming Language/Python/03. Function Building and Block of Code.md
      - Comprehension and Generators : Programming Language/Python/04. Comprehension and Generators.md
      - OPP,  Decorator, and Iterators : Programming Language/Python/05. OPP,  Decorator, and Iterators.md
  - Information Technology:
    - Learn Arduino:
      - Preface Arduino : Technology/Catatan Arduino/index.md
      - Introduce to Arduino : Technology/Catatan Arduino/01. What is arduino.md
      - Getting physical with arduino : Technology/Catatan Arduino/02. Getting physical with arduino.md
      - "Basic Sketches: input, output and communication" : "Technology/Catatan Arduino/03. Basic Sketches: input, output and communication..md"
    - Learn System Analyst:
      - Preface SA : Technology/Catatan System Analys/index.md
      - The System Analyst and System Development: Technology/Catatan System Analys/1. The System Analyst and System Development.md
    - Learn Linux:
      - Linux Bible:
        - Preface Linux: Technology/Catatan Linux Bible/index.md
        - Using The Shell: Technology/Catatan Linux Bible/01. Using the shell.md
        - File system: Technology/Catatan Linux Bible/02. File system.md
        - Additional note: Technology/Catatan Linux Bible/99. Additional notes.md
      - Fundamental Linux | HTB:
        - preface Linux HTB: Technology/Catatan Linux HTB/index.md
        - Filter Content: Technology/Catatan Linux HTB/01. Filtering content.md
        - Regular Expression: Technology/Catatan Linux HTB/02. Regular expression.md
        - Permission Management: Technology/Catatan Linux HTB/03. Permission management.md
        - User Management: Technology/Catatan Linux HTB/04. User management.md
        - Service and Process Management: Technology/Catatan Linux HTB/05.Service and process management.md
        - Task  Scheduling : Technology/Catatan Linux HTB/06. Task  scheduling.md
        - Network Service : Technology/Catatan Linux HTB/07. Network service.md
        - Additional note: Technology/Catatan Linux HTB/99. Additional notes.md
    - Learn MySql:
      - Preface MySql: Technology/Catatan MySql/index.md
      - Rangkuman Muka: Technology/Catatan MySql/01. Rangkuman Muka.md
      - Understanding RDBMS: Technology/Catatan MySql/01. Understanding RDBMS.md
      - Understanding Data Type: Technology/Catatan MySql/02. Understanding The Data Type.md
      - Creating and Designing Database: Technology/Catatan MySql/03. Creating and Designing Database.md
      - Importing and Exporting Data: Technology/Catatan MySql/04. Importing and Exporting Data.md
      - Querying a Single Table: Technology/Catatan MySql/05. Querying a Single Table.md
      - Querying Multiple Tables: Technology/Catatan MySql/06. Querying Multiple Tables.md
      - Modifiying data and Tabel Structure : Technology/Catatan MySql/07. Modifiying data and Tabel Structure.md
      
  - Deen:
    - Random Notes: Deen/Catatan Bunda/index.md





