site_name: Our Notes
site_url: https://github.com/muhammadfarras/kertas-pena
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.top
    - toc.follow
    - toc.integrate
    - header.autohide
    # - navigation.footer
  palette: 
    
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7 
        name: Gelapin
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Terangin
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true 
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  generator: true
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/muhammadfarras
    name: Muhammad Farras Ma'ruf's GitHub
copyright: Catatan untuk, Muhammad Faris Ma'ruf & Nu'man Noah Ma'ruf 2023










nav:
  - index.md
  - Programming Language: 
    - Learn Python:
      - Preface Python: Programming Language/Python/index.md
      - Data Types: Programming Language/Python/01. Data Types.md
  - Information Technology:
    - Learn Linux:
      - Preface Linux: Technology/Catatan Linux Bible/index.md
      - Using The Shell: Technology/Catatan Linux Bible/01. Using the shell.md
    - Learn MySql:
      - Preface MySql: Technology/Catatan MySql/index.md
      - Rangkuman Muka: Technology/Catatan MySql/01. Rangkuman Muka.md
      - Understanding RDBMS: Technology/Catatan MySql/01. Understanding RDBMS.md
      - Understanding Data Type: Technology/Catatan MySql/02. Understanding The Data Type.md
      - Creating and Designing Database: Technology/Catatan MySql/03. Creating and Designing Database.md
      - Importing and Exporting Data: Technology/Catatan MySql/04. Importing and Exporting Data.md
      - Querying a Single Table: Technology/Catatan MySql/05. Querying a Single Table.md
      - Querying Multiple Tables: Technology/Catatan MySql/06. Querying Multiple Tables.md
      - Modifiying data and Tabel Structure : Technology/Catatan MySql/07. Modifiying data and Tabel Structure.md
      
  - Deen:
    - Random Notes: Deen/Catatan Bunda/index.md





